CREATE TABLE crop (
  cropId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (cropId) USING BTREE,
  cropName VARCHAR(30) NOT NULL,
  UNIQUE KEY UNI_FIELDNAME (cropName),
  type varchar(10)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;