CREATE TABLE qualityItem (
  qualityItemId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (qualityItemId) USING BTREE,
  qualityItemName VARCHAR(30) NOT NULL,
  UNIQUE KEY UNI_SUBSTAGENAME (qualityItemName),
  cropId int(10) unsigned not null,
  KEY FK_QUA_CROP_ID (cropId),
  CONSTRAINT FK_QUA_CROP_ID FOREIGN KEY (cropId)
  REFERENCES crop (cropId) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;